web:
    image: bizmate/symfony
    container_name: Bizmate-web
    volumes:
        - .:/var/www/
    ports:
        - "80:80"
        - "443:443"

mysql:
    image: mysql
    container_name: Bizmate-MySQL
    net: "host"
    environment:
        MYSQL_ROOT_PASSWORD: 'toor'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'Bizmate-symfony2016'
        MYSQL_DATABASE: 'bizmate'